export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transaction without fees',
    buttonLabel: 'Get Started',
    imgStart: false,
    img: require('../../images/img-4.png').default,
    alt: 'Mboh',
    dark: true,
    primary: true,
    darkText: false,
    pink: true,
};

export const homeObjTwo = {
    id: 'product',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Blyat Momento',
    headline: 'Ruski Ruski',
    description: 'Get access to our exclusive app that allows you to send unlimited transaction without fees',
    buttonLabel: 'Get Started',
    imgStart: true,
    img: require('../../images/img-1.png').default,
    alt: 'Mboh',
    dark: false,
    primary: false,
    darkText: true,
    pink: false,
};
